export const FETCH_ALL_NEWS_START = 'FETCH_ALL_NEWS_START';
export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS';
export const FETCH_ALL_NEWS_FAIL = 'FETCH_ALL_NEWS_FAIL';

export const GET_COMPARE_ITEMS = 'GET_COMPARE_ITEMS';
export const SET_COMPARE_ITEMS = 'SET_COMPARE_ITEMS';
export const REMOVE_COMPARE_ITEMS = 'REMOVE_COMPARE_ITEMS';