export const FETCH_ALL_NEWS_START = 'FETCH_ALL_NEWS_START';
export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS';
export const FETCH_ALL_NEWS_FAIL = 'FETCH_ALL_NEWS_FAIL';

export const GET_COMPARE_ITEM = 'GET_COMPARE_ITEM';
export const SET_COMPARE_ITEM = 'SET_COMPARE_ITEM';
export const REMOVE_COMPARE_ITEM = 'REMOVE_COMPARE_ITEM';
export const REMOVE_COMPARE_ALL_ITEMS = 'REMOVE_COMPARE_ALL_ITEMS';

export const FETCH_ALL_FORUM_TOPICS_START = 'FETCH_ALL_FORUM_TOPICS_START';
export const FETCH_ALL_FORUM_TOPICS_SUCCESS = 'FETCH_ALL_FORUM_TOPICS_SUCCESS';
export const FETCH_ALL_FORUM_TOPICS_FAIL = 'FETCH_ALL_FORUM_TOPICS_FAIL';