export const FETCH_ALL_FORUM_TOPICS_START = 'FETCH_ALL_FORUM_TOPICS_START';
export const FETCH_ALL_FORUM_TOPICS_SUCCESS = 'FETCH_ALL_FORUM_TOPICS_SUCCESS';
export const FETCH_ALL_FORUM_TOPICS_FAIL = 'FETCH_ALL_FORUM_TOPICS_FAIL';