export const GET_COMPARE_ITEM = 'GET_COMPARE_ITEM';
export const SET_COMPARE_ITEM = 'SET_COMPARE_ITEM';
export const REMOVE_COMPARE_ITEM = 'REMOVE_COMPARE_ITEM';
export const REMOVE_COMPARE_ALL_ITEMS = 'REMOVE_COMPARE_ALL_ITEMS';
